version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/groupup/"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "maven"
    directory: "/backend/"
    schedule:
      interval: "daily"
