stages:
  - Kotlin build
  - Kotlin test
  - Webapp build
  - Webapp test

services:
  - postgres:latest

variables:
  POSTGRES_DB: groupupdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: groupup

cache:
  paths:
    - .m2/repository/
    - target/
    - .yarn
    - node_modules/

Kotlin Build:
  image: maven:3-openjdk-17
  stage: Kotlin build
  script:
    - cd backend
    - mvn compile
  retry: 1

Detekt:
  image: maven:3-openjdk-17
  stage: Kotlin test
  needs: [Kotlin Build]
  script:
    - cd backend
    - mvn detekt:check
  retry: 1

Ktlint:
  image: maven:3-openjdk-17
  stage: Kotlin test
  needs: [Kotlin Build]
  script:
    - cd backend
    - mvn antrun:run@ktlint
  retry: 1

Maven Test:
  image: maven:3-openjdk-17
  stage: Kotlin test
  needs: [ Kotlin Build ]
  script:
    - spring.datasource.url=jdbc:postgresql://postgres:5432/groupupdb
    - cd backend
    - mvn test
  retry: 1

Yarn Build:
  image: node:17.4.0
  stage: Webapp build
  needs: []
  script:
    - cd groupup
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1

Prettier check:
  image: node:17.4.0
  stage: Webapp test
  needs: []
  script:
    - cd groupup
    - npx prettier --check .
  retry: 1

Eslint:
  image: node:17.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - cd groupup
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
  retry: 1
