stages:
  - Kotlin build
  - Webapp build
  - Webapp test

cache:
  paths:
    - .m2/repository/
    - target/
    - .yarn

Build:
  image: maven:3-openjdk-16
  stage: Kotlin build
  script:
    - cd backend 
    - mvn compile
  retry: 1

Yarn Build:
  image: node:16.3.0
  stage: Webapp build
  needs: []
  script:
    - cd groupup
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1

Prettier check:
  image: node:16.3.0
  stage: Webapp test
  needs: []
  script:
    - cd groupup
    - npx prettier --check .
  retry: 1