stages:
  - Kotlin build
  - Webapp build
  - Webapp test

cache:
  paths:
    - .m2/repository/
    - target/
    - .yarn
    - node_modules/

Build:
  image: maven:3-openjdk-17
  stage: Kotlin build
  script:
    - cd backend
    - mvn compile
  retry: 1

Yarn Build:
  image: node:17.4.0
  stage: Webapp build
  needs: []
  script:
    - cd groupup
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn build
  retry: 1

Prettier check:
  image: node:17.4.0
  stage: Webapp test
  needs: []
  script:
    - cd groupup
    - npx prettier --check .
  retry: 1

Eslint:
  image: node:17.4.0
  stage: Webapp test
  needs: [Yarn Build]
  script:
    - cd groupup
    - yarn install --frozen-lockfile --cache-folder .yarn
    - yarn lint
  retry: 1
