version: '3'

services:
  frontend:
    build:
      context: ./groupup
      args:
        - API_URL=http://localhost:8080/api
    depends_on:
      - backend
    ports: 
      - "3000:80"
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - "8080:80"
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: groupup
      POSTGRES_DB: groupupdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
